# Generated by Django 5.2.5 on 2025-08-27 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='description',
        ),
        migrations.RemoveField(
            model_name='image',
            name='collections',
        ),
        migrations.RemoveField(
            model_name='image',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='collection',
            name='images',
            field=models.ManyToManyField(related_name='collections', to='collection.image'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.TextField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='unsplash_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
